server:
  port: 8763
spring:
  application:
    name: discover-client
  main:
    allow-bean-definition-overriding: true #允许bean覆盖
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true #启用熔断
zuul:
  routes:
    user: #自定义名称
      path: /api-user/**  #路由路径
      serviceId: eureka-client #服务名
    order: #自定义名称
      path: /api-order/** #路由路径
      serviceId: discover-client #服务名